repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Utilisez la version de Ruff qui correspond à celle de votre CI, ou la plus récente stable
    rev: v0.9.9 # Cette version est un exemple, vérifiez la plus récente sur le repo Ruff
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
